### ISSUE TITLE
Enhancement: opt-in to C-based (instead of asm) implementation

### ISSUE THREAD

**Issue by pnkfelix** [pnkfelix/cee-scape#2]
I want to prototype a variant of the crate that totally avoids inline asm and uses ("portable"?) C instead.

I ended up posting this crate without that in place because I wasn't sure the best architecture to use for that C dependency. (E.g. should it be a separate crate? Or can I make it a separate file that is conditionally-compiled?)

**Comment by pnkfelix** [comment]
Note that the current implementation leverages generic code by generating [distinct asm blocks](https://github.com/pnkfelix/cee-scape/blob/9df8c66519537b5d67a0e870425036f993140430/src/lib.rs#L331) for each concrete callback `F`.

It wouldn't be reasonable to do that via C code. But we don't have to; we can make the generic C version take the closure environment and the closure code pointer as explicit arguments, and then do the call itself. Its hypothetically a performance hit to do that, but my gut tells me that its not a noticeable performance hit: either you have LTO turned on, in which case I *hope* you'd see enough inlining to boil away the indirection, or you have LTO turned off, in which case you won't see any cross-language inlining anyway and I doubt you'd care about an indirect vs direct call.

**Comment by jeff-davis** [comment]
This seems like a reasonable thing to do. To me it would make sense to fall back to C for unrecognized architectures, or to allow forcing the C version with a feature flag. That would be a nice safety net in case we discover an obscure bug with either the C version or the asm version.

**Comment by pnkfelix** [comment]
Addressed by https://github.com/pnkfelix/cee-scape/pull/21
