### ISSUE TITLE
inline asm is probably broken for PIC

### ISSUE THREAD

**Issue by thomcc** [pnkfelix/cee-scape#9]
Calling (or often using) sym in asm directly generally doesn't work in position independent code (and honestly a bunch of other cases -- `sym` is a very hard feature to use in my experience).

For example, for pic on ELF usually you'll need something like `{}@PLT`, but sometimes you'll need a rip-relative load and indirect call. To me the details are pretty tedious to get right everywhere (especially on 32 bit x86, where I'm not sure if it's possible). I think it's pretty portable to just call via a function pointer, and I doubt in these cases the performance difference is significant, are you open to this?

That said I haven't tried to produce a failure. Maybe this works for some reason I'm not realizing.

I also suspect clobber should be `clobber_abi("C")` (being specific about the ABI doesn't seem beneficial, but I suppose maybe it's a form of documentation?), although it doesn't really matter a ton since I think this only currently supports Linux.

**Comment by pnkfelix** [comment]
> I think it's pretty portable to just call via a function pointer, and I doubt in these cases the performance difference is significant, are you open to this?

Yeah I think I managed to convince myself in https://github.com/pnkfelix/cee-scape/issues/2#issuecomment-1664170010 that the overhead of calling via a function pointer isn't going to have a significant performance impact.

So I'll look into the change you suggest.

Do you have a recommendation for how to exercise PIC more directly, given that my testing so far didn't hit this problem? Maybe a test that leverages dynamic loading+linking in some manner?

**Comment by pnkfelix** [comment]
I removed use of `sym` (and switched to calls via function pointers) in https://github.com/pnkfelix/cee-scape/commit/74e3290577111c7212396ddb7a750c193cd893b8

I am going to close this ticket and open a separate one asking for testing of the PIC scenario.
